# julia-job.sub

universe = vanilla

log = job_$(Cluster).log
error = job_$(Cluster)_$(Process).err
output = job_$(Cluster)_$(Process).out

executable = julia-job.sh

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = julia-1.9.4-linux-x86_64.tar.gz, netmerge.tar.gz, job.sh, pipeline-1i_iv.csv, pipeline-1i_iv.jl, pipelines.jl, plot-fxns.jl, robustness-fxns.jl

request_cpus = 2
request_memory = 8GB
request_disk = 1GB

queue 1